export default {
  statusAnggotaKK: ['Suami', 'Istri', 'Anak', 'Saudara Kandung', 'Saudara Ipar', 'Orang Tua', 'Mertua', 'Lainnya'],
  pendidikan: ['Tidak/Belum Sekolah', 'SD', 'SMP', 'SMA', 'Diploma', 'Strata 1', 'Strata 2', 'Strata 3'],
  kedudukanDiJemaat: ['Jemaat', 'Jemaat Tamu', 'Diaken', 'Penatua', 'Pendeta'],
  kategoriRumah: ['Semi Permanen', 'Permanen', 'Darurat', 'Lainnya'],
  statusRumah: ['Milik Sendiri', 'Kontrak', 'Menumpang', 'Lainnya'],
  statusNikah: ['Belum Menikah/Bujang', 'Nikah Gereja', 'Belum Nikah Gereja', 'Duda Janda'],
  pekerjaan: [
    'Tidak Ada',
    'Pendeta',
    'Pegawai Negeri Sipil',
    'Pegawai Swasta',
    'Wirawasta',
    'TNI/Polri',
    'Dokter',
    'Bidan',
    'Perawat',
    'Apoteker',
    'Pensiunan',
    'Petani',
    'Pembantu Rumah Tangga',
    'Sopir',
    'Tukang',
    'Buruh',
    'Pegawai Gereja',
    'Pelajar',
    'Mahasiswa',
    'Pedagang',
    'Ibu Rumah Tangga',
    'Pegawai Kontrak/Honor',
    'Lainnya',
  ],
  penghasilan: [
    'Tidak Ada',
    'sd. Rp. 750.000',
    'Rp. 750.000 - Rp. 1.500.000',
    'Rp. 1.500.000 - Rp. 2.500.000',
    'Rp. 2.500.000 - Rp. 5.000.000',
    '> Rp. 5.000.000',
  ],
  keterangan: ['Tidak Ada', 'Janda', 'Duda', 'Yatim', 'Piatu', 'Penyandang Cacat'],
  golonganDarah: ['A', 'B', 'AB', 'O'],
  jaminanKesehatan: ['Tidak Ada', 'BPJS/ASKES', 'Asuransi Lain'],
}
